### ISSUE TITLE
Cannot run on macOS

### ISSUE THREAD

**Issue by redeian** [LucasYuNju/leanote-desktop-lite#1]
$ npm run dev

> leanote-desktop-react@0.1.0 dev /Users/redeian/Desktop/polyElect/leanote-desktop-react
> cross-env NODE_ENV=development npm run server & npm start

> leanote-desktop-react@0.1.0 start /Users/redeian/Desktop/polyElect/leanote-desktop-react
> cross-env NODE_ENV=development electron ./

> leanote-desktop-react@0.1.0 server /Users/redeian/Desktop/polyElect/leanote-desktop-react
> cross-env NODE_ENV=development node ./server.js

A Parser-blocking, cross-origin script, http://localhost:3000/assets/vendor/bundle.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, http://localhost:3000/assets/vendor/bundle.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, http://localhost:3000/assets/main/bundle.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at EventEmitter.listen (/Users/redeian/Desktop/polyElect/leanote-desktop-react/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/redeian/Desktop/polyElect/leanote-desktop-react/server.js:19:5)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
npm ERR! node v4.1.1
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! leanote-desktop-react@0.1.0 server: `cross-env NODE_ENV=development node ./server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leanote-desktop-react@0.1.0 server script 'cross-env NODE_ENV=development node ./server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leanote-desktop-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node ./server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leanote-desktop-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leanote-desktop-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/redeian/Desktop/polyElect/leanote-desktop-react/npm-debug.log

**Comment by LucasYuNju** [comment]
Bug fixed. Thanks.

**Comment by redeian** [comment]
It works. Thanks
